// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpXc9oSM2qCqJfRg3JvR6woIVZDurD3Lo',
    appId: '1:259082467594:web:46598a21343dee2d7062f3',
    messagingSenderId: '259082467594',
    projectId: 'gpt-flyer-chat',
    authDomain: 'gpt-flyer-chat.firebaseapp.com',
    storageBucket: 'gpt-flyer-chat.appspot.com',
    measurementId: 'G-G2G6Q78MJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApeNMMdoF2Lho66xz1OBh0LNmWyR41jV4',
    appId: '1:259082467594:android:3d469426150e54a97062f3',
    messagingSenderId: '259082467594',
    projectId: 'gpt-flyer-chat',
    storageBucket: 'gpt-flyer-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbIausk8og9uuCQFSq6BfOCJtHn3CUN58',
    appId: '1:259082467594:ios:0fe588dd5d2d16bc7062f3',
    messagingSenderId: '259082467594',
    projectId: 'gpt-flyer-chat',
    storageBucket: 'gpt-flyer-chat.appspot.com',
    iosClientId: '259082467594-37qshm525qp7nllu3n42noqiphfj73hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gptChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbIausk8og9uuCQFSq6BfOCJtHn3CUN58',
    appId: '1:259082467594:ios:0fe588dd5d2d16bc7062f3',
    messagingSenderId: '259082467594',
    projectId: 'gpt-flyer-chat',
    storageBucket: 'gpt-flyer-chat.appspot.com',
    iosClientId: '259082467594-37qshm525qp7nllu3n42noqiphfj73hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gptChat',
  );
}
